plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
markdown: kramdown
  usemathjax: true
  math_engine: mathjax  # default in Kramdown
theme: jekyll-theme-minimal

